### ISSUE TITLE
hello, can you share the dataset you used with me?thanks a lot!

### ISSUE THREAD

**Issue by parkourlrc** [rachidoutaleb/LSTM-Based-Malicious-Traffic-Detection#1]
hello, can you share the dataset you used with me?thanks a lot!

**Comment by rachidoutaleb** [comment]
Okay, give me your email and I will send it to you

**Comment by rachidoutaleb** [comment]
> hello, can you share the dataset you used with me?thanks a lot!

**Comment by rachidoutaleb** [comment]
> hello, can you share the dataset you used with me?thanks a lot!

Okay, give me your email and I will send it to you

**Comment by parkourlrc** [comment]
thanks，it's l15698229938@163.com

**Comment by rachidoutaleb** [comment]
> thanks，it's [l15698229938@163.com](mailto:l15698229938@163.com)

done
